apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: models
  name: models
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: models
    spec:
      containers:
      - args:
        - bash
        - models-up.dev.sh
        image: tp33/django
        name: models
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: models-claim0
      restartPolicy: Always
      volumes:
      - name: models-claim0
        persistentVolumeClaim:
          claimName: models-claim0
status: {}
